import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createAuthorization} from '../background/authorization.js';
import {createVerifier} from '../shared/crypto.js';
const password='test-pin-123';
async function fixture(){
 const local={padlox_config:await createVerifier(password),padlox_sites:{'example.com':{addedAt:1}}};const session={};let time=100000;let documentId='doc-a';
 const area=data=>({get:async k=>Object.fromEntries((Array.isArray(k)?k:[k]).map(x=>[x,structuredClone(data[x])])),set:async v=>Object.assign(data,structuredClone(v)),remove:async k=>{for(const x of Array.isArray(k)?k:[k])delete data[x]}});
 const chrome={runtime:{id:'padlox',getURL:p=>'chrome-extension://padlox/'+p},storage:{local:area(local),session:area(session)},tabs:{get:async id=>({id,url:'https://example.com/'})},permissions:{contains:async()=>true,remove:async()=>true},scripting:{executeScript:async()=>[{documentId}],getRegisteredContentScripts:async()=>[],registerContentScripts:async()=>{},unregisterContentScripts:async()=>{}}};
 const popup={id:'padlox',url:chrome.runtime.getURL('popup/popup.html')};const settings={id:'padlox',url:chrome.runtime.getURL('settings/settings.html'),tab:{id:3},documentId:'settings-a',frameId:0};const content={id:'padlox',url:'https://example.com/',tab:{id:1},documentId:'doc-a',frameId:0};
 return {local,session,chrome,popup,settings,content,handle:createAuthorization(chrome,()=>time),tick:()=>time+=16000,navigate:()=>documentId='doc-b'};
}
test('rejects content mutation, forged sender, unknown action and extra payload',async()=>{const f=await fixture();for(const [msg,sender]of [[{action:'RESET',password},f.content],[{action:'UNLOCK',documentId:'doc-a',tabId:1,password},{...f.popup,id:'other'}],[{action:'UNKNOWN'},f.popup],[{action:'STATUS',password},f.content]])assert.equal((await f.handle(msg,sender)).ok,false);assert(f.local.padlox_config)});
test('Settings list requires authentication bound to its document',async()=>{const f=await fixture();assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false);assert((await f.handle({action:'AUTH_SETTINGS',password},f.settings)).ok);assert((await f.handle({action:'LIST_SITES'},f.settings)).ok);assert.equal((await f.handle({action:'LIST_SITES'},{...f.settings,documentId:'other'})).ok,false)});
test('unlock is restricted to one tab and document; reload requires password',async()=>{const f=await fixture();assert((await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup)).ok);assert((await f.handle({action:'STATUS'},f.content)).unlocked);assert.equal((await f.handle({action:'STATUS'},{...f.content,tab:{id:2}})).unlocked,false);f.navigate();assert.equal((await f.handle({action:'STATUS'},{...f.content,documentId:'doc-b'})).unlocked,false)});
test('concurrent incorrect attempts share a serialized cooldown across actions',async()=>{const f=await fixture();const results=await Promise.all([f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password:'wrong'},f.popup),f.handle({action:'AUTH_SETTINGS',password:'wrong'},f.settings)]);assert(results.every(r=>!r.ok));assert.equal(f.session.padlox_auth_attempts.count,1);assert(results.some(r=>r.error.includes('Try again')))});
test('destructive actions require Settings grant and fresh password',async()=>{const f=await fixture();assert.equal((await f.handle({action:'RESET',password},f.settings)).ok,false);await f.handle({action:'AUTH_SETTINGS',password},f.settings);assert.equal((await f.handle({action:'REMOVE_SITE',domain:'example.com',password:'wrong'},f.settings)).ok,false);assert(f.local.padlox_sites['example.com']);f.tick();assert((await f.handle({action:'REMOVE_SITE',domain:'example.com',password},f.settings)).ok);assert.deepEqual(f.local.padlox_sites,{})});
test('worker recreation retains authorization state, password change revokes it',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);await f.handle({action:'AUTH_SETTINGS',password},f.settings);const restarted=createAuthorization(f.chrome);assert((await restarted({action:'STATUS'},f.content)).unlocked);assert((await f.handle({action:'CHANGE_PASSWORD',password,next:'new-pin-456'},f.settings)).ok);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false)});
test('content status reveals only protection flags and rejects subframes/missing document IDs',async()=>{const f=await fixture();const status=await f.handle({action:'STATUS'},f.content);assert.deepEqual(Object.keys(status).sort(),['ok','protected','unlocked']);for(const sender of [{...f.content,frameId:1},{...f.content,documentId:undefined},{...f.settings,url:'https://attacker.test/'}])assert.equal((await f.handle({action:'AUTH_SETTINGS',password},sender)).ok,false)});
test('navigation during password verification never authorizes the replacement document',async()=>{const f=await fixture();let calls=0;f.chrome.scripting.executeScript=async()=>[{documentId:++calls===1?'old':'new'}];assert.equal((await f.handle({action:'UNLOCK',documentId:'old',tabId:1,password},f.popup)).ok,false);assert.equal(f.session.padlox_tab_unlocks,undefined)});
test('Lock now affects only the chosen tab',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:2,password},f.popup);await f.handle({action:'LOCK',tabId:1},f.popup);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);assert((await f.handle({action:'STATUS'},{...f.content,tab:{id:2}})).unlocked)});
test('Settings grants expire and never authorize password changes afterward',async()=>{const f=await fixture();await f.handle({action:'AUTH_SETTINGS',password},f.settings);for(let i=0;i<19;i++)f.tick();assert.equal((await f.handle({action:'CHANGE_PASSWORD',password,next:'changed'},f.settings)).ok,false);assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false)});
test('protection requires permission and never implicitly grants an unlock',async()=>{const f=await fixture();f.chrome.permissions.contains=async()=>false;assert.equal((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok,false);f.chrome.permissions.contains=async()=>true;assert((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false)});
test('registration failure leaves site list and unlock state unchanged',async()=>{const f=await fixture();f.chrome.tabs.get=async id=>({id,url:'https://other.test/'});f.chrome.scripting.registerContentScripts=async()=>{throw Error('registration failed')};assert.equal((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok,false);assert.deepEqual(Object.keys(f.local.padlox_sites),['example.com']);assert.equal(f.session.padlox_tab_unlocks,undefined)});
test('initial setup cannot overwrite an existing password or silently reset protected sites',async()=>{const f=await fixture();assert.equal((await f.handle({action:'SETUP',password:'changed'},f.popup)).ok,false);delete f.local.padlox_config;assert.equal((await f.handle({action:'SETUP',password:'changed'},f.popup)).ok,false)});
test('closed tabs lose unlocks and Settings grants without affecting other tabs',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);await f.handle({action:'AUTH_SETTINGS',password},f.settings);await f.handle.clearTab(1);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);await f.handle.clearTab(3);assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false)});

test('popup cannot unlock a different document than the one displayed',async()=>{const f=await fixture();f.navigate();assert.equal((await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup)).ok,false);assert.equal(f.session.padlox_tab_unlocks,undefined)});
