import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createAuthorization} from '../background/authorization.js';
import {createVerifier} from '../shared/crypto.js';
const password='test-pin-123';
async function fixture(){
 const local={padlox_config:await createVerifier(password),padlox_sites:{'example.com':{addedAt:1}}};const session={};let time=100000;let documentId='doc-a';
 const area=data=>({get:async k=>Object.fromEntries((Array.isArray(k)?k:[k]).map(x=>[x,structuredClone(data[x])])),set:async v=>Object.assign(data,structuredClone(v)),remove:async k=>{for(const x of Array.isArray(k)?k:[k])delete data[x]}});
 const chrome={runtime:{id:'padlox',getURL:p=>'chrome-extension://padlox/'+p},storage:{local:area(local),session:area(session)},tabs:{get:async id=>({id,url:'https://example.com/'})},permissions:{contains:async()=>true,remove:async()=>true},scripting:{executeScript:async()=>[{documentId}],getRegisteredContentScripts:async()=>[{id:'padlox-example.com',matches:['*://example.com/*','*://*.example.com/*'],js:['content/lock.js'],runAt:'document_start',world:'ISOLATED',persistAcrossSessions:true}],registerContentScripts:async()=>{},unregisterContentScripts:async()=>{}}};
 const popup={id:'padlox',url:chrome.runtime.getURL('popup/popup.html')};const settings={id:'padlox',url:chrome.runtime.getURL('settings/settings.html'),tab:{id:3},documentId:'settings-a',frameId:0};const content={id:'padlox',url:'https://example.com/',tab:{id:1},documentId:'doc-a',frameId:0};
 return {local,session,chrome,popup,settings,content,handle:createAuthorization(chrome,()=>time),tick:()=>time+=16000,advance:ms=>time+=ms,time:()=>time,navigate:()=>documentId='doc-b'};
}
test('rejects content mutation, forged sender, unknown action and extra payload',async()=>{const f=await fixture();for(const [msg,sender]of [[{action:'RESET',password},f.content],[{action:'UNLOCK',documentId:'doc-a',tabId:1,password},{...f.popup,id:'other'}],[{action:'UNKNOWN'},f.popup],[{action:'STATUS',password},f.content]])assert.equal((await f.handle(msg,sender)).ok,false);assert(f.local.padlox_config)});
test('Settings list requires authentication bound to its document',async()=>{const f=await fixture();assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false);assert((await f.handle({action:'AUTH_SETTINGS',password},f.settings)).ok);assert((await f.handle({action:'LIST_SITES'},f.settings)).ok);assert.equal((await f.handle({action:'LIST_SITES'},{...f.settings,documentId:'other'})).ok,false)});
test('unlock is restricted to one tab and document; reload requires password',async()=>{const f=await fixture();assert((await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup)).ok);assert((await f.handle({action:'STATUS'},f.content)).unlocked);assert.equal((await f.handle({action:'STATUS'},{...f.content,tab:{id:2}})).unlocked,false);f.navigate();assert.equal((await f.handle({action:'STATUS'},{...f.content,documentId:'doc-b'})).unlocked,false)});
test('concurrent incorrect attempts share a serialized cooldown across actions',async()=>{const f=await fixture();const results=await Promise.all([f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password:'wrong'},f.popup),f.handle({action:'AUTH_SETTINGS',password:'wrong'},f.settings)]);assert(results.every(r=>!r.ok));assert.equal(f.local.padlox_auth_attempts.count,1);assert(results.some(r=>r.error.includes('Try again')))});
test('destructive actions require Settings grant and fresh password',async()=>{const f=await fixture();assert.equal((await f.handle({action:'RESET',password},f.settings)).ok,false);await f.handle({action:'AUTH_SETTINGS',password},f.settings);assert.equal((await f.handle({action:'REMOVE_SITE',domain:'example.com',password:'wrong'},f.settings)).ok,false);assert(f.local.padlox_sites['example.com']);f.tick();assert((await f.handle({action:'REMOVE_SITE',domain:'example.com',password},f.settings)).ok);assert.deepEqual(f.local.padlox_sites,{})});
test('worker recreation retains authorization state, password change revokes it',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);await f.handle({action:'AUTH_SETTINGS',password},f.settings);const restarted=createAuthorization(f.chrome);assert((await restarted({action:'STATUS'},f.content)).unlocked);assert((await f.handle({action:'CHANGE_PASSWORD',password,next:'new-pin-456'},f.settings)).ok);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false)});
test('content status reveals only protection flags and rejects subframes/missing document IDs',async()=>{const f=await fixture();const status=await f.handle({action:'STATUS'},f.content);assert.deepEqual(Object.keys(status).sort(),['ok','protected','unlocked']);for(const sender of [{...f.content,frameId:1},{...f.content,documentId:undefined},{...f.settings,url:'https://attacker.test/'}])assert.equal((await f.handle({action:'AUTH_SETTINGS',password},sender)).ok,false)});
test('navigation during password verification never authorizes the replacement document',async()=>{const f=await fixture();let calls=0;f.chrome.scripting.executeScript=async()=>[{documentId:++calls===1?'old':'new'}];assert.equal((await f.handle({action:'UNLOCK',documentId:'old',tabId:1,password},f.popup)).ok,false);assert.equal(f.session.padlox_tab_unlocks,undefined)});
test('Lock now affects only the chosen tab',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:2,password},f.popup);await f.handle({action:'LOCK',tabId:1},f.popup);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);assert((await f.handle({action:'STATUS'},{...f.content,tab:{id:2}})).unlocked)});
test('Settings grants expire and never authorize password changes afterward',async()=>{const f=await fixture();await f.handle({action:'AUTH_SETTINGS',password},f.settings);for(let i=0;i<19;i++)f.tick();assert.equal((await f.handle({action:'CHANGE_PASSWORD',password,next:'changed'},f.settings)).ok,false);assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false)});
test('protection requires permission and never implicitly grants an unlock',async()=>{const f=await fixture();f.chrome.permissions.contains=async()=>false;assert.equal((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok,false);f.chrome.permissions.contains=async()=>true;assert((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false)});
test('registration failure leaves site list and unlock state unchanged',async()=>{const f=await fixture();f.chrome.tabs.get=async id=>({id,url:'https://other.test/'});f.chrome.scripting.registerContentScripts=async()=>{throw Error('registration failed')};assert.equal((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok,false);assert.deepEqual(Object.keys(f.local.padlox_sites),['example.com']);assert.equal(f.session.padlox_tab_unlocks,undefined)});
test('initial setup cannot overwrite an existing password or silently reset protected sites',async()=>{const f=await fixture();assert.equal((await f.handle({action:'SETUP',password:'changed'},f.popup)).ok,false);delete f.local.padlox_config;assert.equal((await f.handle({action:'SETUP',password:'changed'},f.popup)).ok,false)});
test('closed tabs lose unlocks and Settings grants without affecting other tabs',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);await f.handle({action:'AUTH_SETTINGS',password},f.settings);await f.handle.clearTab(1);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);await f.handle.clearTab(3);assert.equal((await f.handle({action:'LIST_SITES'},f.settings)).ok,false)});

test('popup cannot unlock a different document than the one displayed',async()=>{const f=await fixture();f.navigate();assert.equal((await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup)).ok,false);assert.equal(f.session.padlox_tab_unlocks,undefined)});
test('cooldown survives browser-session loss and successful authentication clears it',async()=>{const f=await fixture();await f.handle({action:'AUTH_SETTINGS',password:'wrong'},f.settings);for(const key of Object.keys(f.session))delete f.session[key];const restarted=createAuthorization(f.chrome,()=>100000);const result=await restarted({action:'AUTH_SETTINGS',password},f.settings);assert.equal(result.ok,false);assert.match(result.error,/Try again/);f.tick();assert((await f.handle({action:'AUTH_SETTINGS',password},f.settings)).ok);assert.equal(f.local.padlox_auth_attempts,undefined)});
test('new passwords require six-digit PIN or eight-character password, legacy PIN still works',async()=>{const f=await fixture();f.local.padlox_config=await createVerifier('1234');assert((await f.handle({action:'AUTH_SETTINGS',password:'1234'},f.settings)).ok);for(const next of ['1234','12345','abcdefg','        '])assert.equal((await f.handle({action:'CHANGE_PASSWORD',password:'1234',next},f.settings)).ok,false);assert((await f.handle({action:'CHANGE_PASSWORD',password:'1234',next:'123456'},f.settings)).ok)});
test('revoked permission blocks unlock and invalidates previous authorization',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);f.chrome.permissions.contains=async()=>false;assert.equal((await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup)).ok,false);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false);const state=await f.handle({action:'POPUP_STATE',tabId:1},f.popup);assert.equal(state.needsPermission,true);f.chrome.permissions.contains=async()=>true;assert((await f.handle({action:'PROTECT',tabId:1},f.popup)).ok);assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false)});
test('reconciliation removes stale registrations, keeps requested protection and recovers restored access',async()=>{const f=await fixture();let registered=[{id:'padlox-example.com',matches:['*://example.com/*','*://*.example.com/*'],js:['content/lock.js'],runAt:'document_start',world:'ISOLATED',persistAcrossSessions:true}];f.chrome.permissions.contains=async()=>false;f.chrome.scripting.getRegisteredContentScripts=async()=>registered;f.chrome.scripting.unregisterContentScripts=async()=>{registered=[]};assert((await f.handle.reconcile()).ok);assert.deepEqual(registered,[]);assert(f.local.padlox_sites['example.com']);f.chrome.permissions.contains=async()=>true;f.chrome.scripting.registerContentScripts=async scripts=>{registered=scripts};assert((await f.handle.reconcile()).ok);assert.equal(registered[0].id,'padlox-example.com')});
test('normal worker recovery preserves healthy document unlocks and migrates legacy cooldown',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);f.session.padlox_auth_attempts={count:1,lockUntil:101000};assert((await f.handle.reconcile(false)).ok);assert((await f.handle({action:'STATUS'},f.content)).unlocked);assert.equal(f.local.padlox_auth_attempts.count,1)});
test('worker recovery repairs mismatched script configuration and clears stale unlocks',async()=>{const f=await fixture();await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup);let script={id:'padlox-example.com',matches:['*://example.com/*'],js:['content/lock.js'],runAt:'document_idle'};f.chrome.scripting.getRegisteredContentScripts=async()=>script?[script]:[];f.chrome.scripting.unregisterContentScripts=async()=>{script=null};f.chrome.scripting.registerContentScripts=async scripts=>{script=scripts[0]};assert((await f.handle.reconcile(false)).ok);assert.equal(script.runAt,'document_start');assert.equal((await f.handle({action:'STATUS'},f.content)).unlocked,false)});
test('persistent cooldown grows exponentially and caps at fifteen minutes',async()=>{
 const f=await fixture();
 for(let count=1;count<=15;count++){
  f.advance(16*60*1000);
  assert.equal((await f.handle({action:'AUTH_SETTINGS',password:'wrong'},f.settings)).ok,false);
  assert.equal(f.local.padlox_auth_attempts.lockUntil-f.time(),Math.min(1000*2**(count-1),15*60*1000));
 }
 const before=f.local.padlox_auth_attempts.lockUntil;
 assert.equal((await f.handle({action:'AUTH_SETTINGS',password},f.settings)).ok,false);
 assert.equal(f.local.padlox_auth_attempts.lockUntil,before);
});
test('permission change during verification cannot authorize an unlock',async()=>{const f=await fixture();let calls=0;f.chrome.scripting.executeScript=async()=>{if(++calls===2)f.chrome.permissions.contains=async()=>false;return [{documentId:'doc-a'}]};assert.equal((await f.handle({action:'UNLOCK',documentId:'doc-a',tabId:1,password},f.popup)).ok,false);assert.equal(f.session.padlox_tab_unlocks,undefined)});
test('corrupt attempt counters and protected-site storage fail closed',async()=>{const f=await fixture();f.local.padlox_auth_attempts=0;assert.equal((await f.handle({action:'AUTH_SETTINGS',password},f.settings)).ok,false);delete f.local.padlox_auth_attempts;f.local.padlox_sites=null;assert.equal((await f.handle({action:'STATUS'},f.content)).ok,false)});
